export enum ColorsType {
  black = '#000',
  white = '#fff',
  backgrond_blue = '#3b6ea5',
  backgrond_gray = '#d4d0c7',
  soft_blue = '#3b87a5',
  soft_sky_blue = '#3ba5a1',
  soft_emerald_green = '#3ba565',
  soft_green = '#87a53b',
  soft_yellow = '#a5a03b',
  soft_red = '#a53b3b',
  soft_pink = '#a53b9e',
  soft_purple = '#4d3ba5',
  shock_blue = '#1500ff',
  shock_sky_blue = '#00ffff',
  shock_yellow = '#ffff00',
  shock_red = '#ff0000',
  shock_green = '#00ff00',
  modal_shadow_black = '#2b2b2b',
  modal_shadow_white = '#dadada',
  modal_shadow_more_white = '#f0f0f0',
  modal_background = '#afafaf',
}
